name: mp4
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  audioplayers: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
   - assets/audio/1.mp3
   - assets/audio/2.mp3
   - assets/audio/3.mp3
   - assets/audio/4.mp3
   - assets/audio/5.mp3
   - assets/audio/6.mp3
   - assets/audio/7.mp3
   - assets/audio/8.mp3
   - assets/audio/9.mp3
   - assets/audio/10.mp3
   - assets/audio/11.mp3
   - assets/audio/12.mp3
   - assets/audio/13.mp3

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
